# Generated by Django 4.1.3 on 2023-11-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplypoint', models.CharField(max_length=3, null=True)),
                ('categoria_componente', models.CharField(max_length=3, null=True)),
                ('cdgrupo', models.CharField(max_length=4, null=True)),
                ('grupo', models.CharField(max_length=255, null=True)),
                ('cdsubgrupo', models.CharField(max_length=6, null=True)),
                ('subgrupo', models.CharField(max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255, null=True)),
                ('unidmedida', models.CharField(max_length=2, null=True)),
                ('procedencia', models.CharField(max_length=255, null=True)),
                ('cdantigo', models.CharField(max_length=255, null=True)),
                ('cdcrm', models.CharField(max_length=50)),
                ('preferencial', models.BooleanField(null=True)),
                ('conexao', models.CharField(max_length=1, null=True)),
                ('potencia', models.DecimalField(decimal_places=3, max_digits=100, null=True)),
                ('comprimento', models.IntegerField(null=True)),
                ('largura', models.IntegerField(null=True)),
                ('altura', models.IntegerField(null=True)),
                ('correnteac', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('correntedc', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('tensaoac', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('tensaodc', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('orientacao_mptt', models.IntegerField(null=True)),
                ('preco', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('qtd_estoque', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('inv_requer_stringbox', models.BooleanField(null=True)),
                ('cabo_ac_mm', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('stringbox_qtd_inout', models.IntegerField(null=True)),
                ('qtd_disjuntores', models.IntegerField(null=True)),
                ('tensao_primario', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('tensao_secundario', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.brand')),
            ],
            options={
                'verbose_name': 'componente',
                'verbose_name_plural': 'componentes',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('power_plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.customer')),
            ],
            options={
                'verbose_name': 'PowerPlant',
                'verbose_name_plural': 'PowerPlants',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.component')),
                ('power_plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.powerplant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
