# Generated by Django 4.1.3 on 2023-11-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='power_plant_id',
            new_name='power_plant',
        ),
        migrations.RenameField(
            model_name='powerplant',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
