# Generated by Django 4.1.3 on 2023-11-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0003_alter_component_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='DBBrand',
        ),
        migrations.RenameModel(
            old_name='Component',
            new_name='DBComponent',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='DBCustomer',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='DBOrder',
        ),
        migrations.RenameModel(
            old_name='PowerPlant',
            new_name='DBPowerPlant',
        ),
    ]
