# Generated by Django 4.1.3 on 2023-11-16 16:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0004_rename_brand_dbbrand_rename_component_dbcomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBVoltage',
            fields=[
                ('voltage_id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_to_phase', models.IntegerField()),
                ('phase_to_neutral', models.IntegerField()),
            ],
            options={
                'verbose_name': 'DBVoltage',
                'verbose_name_plural': 'DBVoltages',
            },
        ),
        migrations.CreateModel(
            name='DBModule',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('nominal_power', models.IntegerField()),
                ('operating_voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('operating_current', models.DecimalField(decimal_places=2, max_digits=5)),
                ('open_circuit_voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('short_circuit_current', models.DecimalField(decimal_places=2, max_digits=5)),
                ('module_efficiency', models.DecimalField(decimal_places=2, max_digits=2)),
                ('operating_temperature', models.DecimalField(decimal_places=2, max_digits=2)),
                ('max_system_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbbrand')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbcomponent')),
            ],
            options={
                'verbose_name': 'DBModule',
                'verbose_name_plural': 'DBModules',
            },
        ),
        migrations.CreateModel(
            name='DBInverter',
            fields=[
                ('inverter_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('cc_max_pv_power', models.IntegerField()),
                ('cc_max_input_voltage', models.IntegerField()),
                ('cc_startup_input_voltage', models.IntegerField()),
                ('cc_num_mppt', models.IntegerField()),
                ('cc_mppt_voltage_range_min', models.IntegerField()),
                ('cc_mppt_voltage_range_max', models.IntegerField()),
                ('cc_max_input_current', models.IntegerField()),
                ('cc_max_short_circuit_current', models.IntegerField()),
                ('cc_num_inputs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('ca_power', models.IntegerField()),
                ('ca_max_power', models.IntegerField()),
                ('ca_connection_type', models.CharField(max_length=3)),
                ('ca_current', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ca_max_current', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbbrand')),
                ('ca_voltage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculibrium.dbvoltage')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbcomponent')),
            ],
            options={
                'verbose_name': 'DBInverter',
                'verbose_name_plural': 'DBInverter',
            },
        ),
    ]
