# Generated by Django 4.1.3 on 2023-11-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0006_remove_dbmodule_module_efficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmodule',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbcomponent'),
        ),
    ]
