# Generated by Django 4.1.3 on 2023-11-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0008_dbmodule_bifacial'),
    ]

    operations = [

    ]
