# Generated by Django 4.1.3 on 2023-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0009_dbinverter_ca_isc_max_secundary_and_more'),
    ]

    operations = [
        
    ]
