# Generated by Django 4.1.3 on 2023-11-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0010_alter_dbinverter_ca_max_power_and_more'),
    ]

    operations = [

    ]
