# Generated by Django 4.1.3 on 2023-11-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0011_alter_dbinverter_weight'),
    ]

    operations = [

    ]
