# Generated by Django 4.1.3 on 2023-11-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0012_delete_dbinverter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBInverter',
            fields=[
                ('inverter_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('cc_max_pv_power', models.IntegerField(default=0)),
                ('cc_max_input_voltage', models.IntegerField(default=0)),
                ('cc_startup_input_voltage', models.IntegerField(default=0)),
                ('cc_mppt_voltage_range_min', models.IntegerField(default=0)),
                ('cc_mppt_voltage_range_max', models.IntegerField(default=0)),
                ('cc_max_input_current', models.IntegerField(default=0)),
                ('cc_max_short_circuit_current', models.IntegerField(default=0)),
                ('cc_num_mppt', models.IntegerField(default=0)),
                ('cc_isc_max_main', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ca_isc_max_secundary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cc_num_inputs', models.IntegerField(default=0)),
                ('cc_num_inputs_main', models.IntegerField(null=True)),
                ('cc_num_inputs_secundary', models.IntegerField(null=True)),
                ('cc_mppt_desbalanced', models.BooleanField(default=0)),
                ('ca_power', models.IntegerField(default=0)),
                ('ca_max_power', models.IntegerField(default=0)),
                ('ca_connection_type', models.CharField(max_length=3)),
                ('ca_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ca_max_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbbrand')),
                ('ca_voltage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculibrium.dbvoltage')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbcomponent')),
            ],
            options={
                'verbose_name': 'DBInverter',
                'verbose_name_plural': 'DBInverter',
            },
        ),
    ]
