# Generated by Django 4.1.3 on 2023-11-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0013_dbinverter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinverter',
            name='brand',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbbrand'),
        ),
        migrations.AlterField(
            model_name='dbinverter',
            name='ca_voltage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='calculibrium.dbvoltage'),
        ),
        migrations.AlterField(
            model_name='dbinverter',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbcomponent'),
        ),
    ]
