# Generated by Django 4.1.3 on 2023-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0017_alter_dbinverter_ca_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinverter',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dbinverter',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dbinverter',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
