# Generated by Django 4.1.3 on 2023-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0019_dbmaterial_remove_dbinverter_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcable',
            name='cable_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dbmaterial',
            name='material_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
