# Generated by Django 4.1.3 on 2023-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0020_alter_dbcable_cable_id_alter_dbmaterial_material_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbcable',
            name='resistivity',
        ),
        migrations.AddField(
            model_name='dbmaterial',
            name='resistivity',
            field=models.FloatField(default=0),
        ),
    ]
