# Generated by Django 4.1.3 on 2023-11-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0022_rename_external_area_dbcable_external_diameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbbrand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='dbcable',
            options={'verbose_name': 'Cabo Flex', 'verbose_name_plural': 'Cabos Flex'},
        ),
        migrations.AlterModelOptions(
            name='dbcomponent',
            options={'managed': True, 'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.AlterModelOptions(
            name='dbinverter',
            options={'verbose_name': 'Inversor', 'verbose_name_plural': 'Inversores'},
        ),
        migrations.AlterModelOptions(
            name='dbmaterial',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='dbmodule',
            options={'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='dbvoltage',
            options={'verbose_name': 'Tensão', 'verbose_name_plural': 'Tensões'},
        ),
    ]
