# Generated by Django 4.1.3 on 2023-11-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0025_alter_dbinverter_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcircuitbreaker',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculibrium.dbbrand'),
        ),
    ]
