# Generated by Django 4.1.3 on 2023-11-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0026_dbcircuitbreaker_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcircuitbreaker',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
