# Generated by Django 4.1.3 on 2023-11-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculibrium', '0027_alter_dbcircuitbreaker_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBCable',
            new_name='DBCableFlex',
        ),
    ]
